//
//  WelcomeInteractor.swift
//  joserodriguez
//
//  Created WHIZ on 23/12/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class WelcomeInteractor: WelcomeInteractorInputProtocol {
    weak var presenter: WelcomeInteractorOutputProtocol?
}
