//
//  WelcomeViewController.swift
//  joserodriguez
//
//  Created WHIZ on 23/12/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class WelcomeViewController: UIViewController, WelcomeViewProtocol {
	var presenter: WelcomePresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    
    @IBAction func buttonInitaction(_ sender: Any) {
        
        if RemoteLib.shared.settingsManager.save {
          
            let vc = LocationRouter.createModule()
            self.navigationController?.pushViewController(vc, animated: true)
            
            
        } else {
            let vc =  RegisterRouter.createModule()
            self.navigationController?.pushViewController(vc, animated: true)
            
       
        }
        
        
    }
    
    
}
